-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
